import type { StartupAnalysis } from "@/lib/parse-analysis";

export function exportLandingPageHtml(analysis: StartupAnalysis): void {
  const lp = analysis.landingPage;
  if (!lp) return;

  const pricing = analysis.monetization?.pricingTiers || [];

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${lp.hero?.headline || "Landing Page"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; }
  </style>
</head>
<body class="bg-white text-gray-900">
  <!-- Hero -->
  <section class="min-h-[70vh] flex flex-col items-center justify-center text-center px-6 py-20 bg-gradient-to-br from-indigo-600 to-purple-700 text-white">
    <h1 class="text-4xl md:text-6xl font-bold max-w-3xl mb-6">${lp.hero?.headline || ""}</h1>
    <p class="text-lg md:text-xl max-w-2xl mb-8 opacity-90">${lp.hero?.subheadline || ""}</p>
    <a href="#" class="bg-white text-indigo-700 font-semibold px-8 py-3 rounded-lg text-lg hover:bg-gray-100 transition">${lp.hero?.cta || "Get Started"}</a>
  </section>

  <!-- Features -->
  ${lp.features?.length ? `
  <section class="py-20 px-6 max-w-6xl mx-auto">
    <h2 class="text-3xl font-bold text-center mb-12">Features</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      ${lp.features.map(f => `
      <div class="p-6 rounded-xl border border-gray-200 hover:shadow-lg transition">
        <h3 class="text-xl font-semibold mb-2">${f.title}</h3>
        <p class="text-gray-600">${f.description}</p>
      </div>`).join("")}
    </div>
  </section>` : ""}

  <!-- Pricing -->
  ${pricing.length ? `
  <section class="py-20 px-6 bg-gray-50">
    <div class="max-w-6xl mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">Pricing</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-${Math.min(pricing.length, 4)} gap-8">
        ${pricing.map(t => `
        <div class="bg-white p-8 rounded-xl border border-gray-200 text-center">
          <h3 class="text-xl font-semibold mb-2">${t.name}</h3>
          <p class="text-3xl font-bold text-indigo-600 mb-6">${t.price}</p>
          <ul class="text-left space-y-2 text-gray-600 mb-8">
            ${(t.features || []).map(f => `<li class="flex items-center gap-2"><span class="text-green-500">✓</span> ${f}</li>`).join("")}
          </ul>
          <a href="#" class="block bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700 transition">Choose Plan</a>
        </div>`).join("")}
      </div>
    </div>
  </section>` : ""}

  <!-- CTA -->
  <section class="py-20 px-6 text-center">
    <h2 class="text-3xl font-bold mb-4">${lp.finalCta || "Ready to get started?"}</h2>
    <a href="#" class="inline-block bg-indigo-600 text-white font-semibold px-8 py-3 rounded-lg text-lg hover:bg-indigo-700 transition">${lp.hero?.cta || "Get Started"}</a>
  </section>

  <footer class="py-8 text-center text-gray-400 text-sm border-t">
    <p>Generated by AI Product Manager</p>
  </footer>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "landing-page.html";
  a.click();
  URL.revokeObjectURL(url);
}
