import { useState, useEffect, useRef, useCallback } from "react";
import type { StartupAnalysis } from "@/lib/parse-analysis";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { shareOnLinkedIn, shareOnTwitter, shareNative } from "@/lib/social-share";
import {
  Play, Pause, SkipForward, SkipBack, Video, Linkedin, Twitter, Share2,
  Download, Maximize2, Minimize2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import html2canvas from "html2canvas";

interface Props {
  analysis: StartupAnalysis;
  idea: string;
}

interface Slide {
  title: string;
  subtitle: string;
  content: React.ReactNode;
  narration: string;
  bgGradient: string;
  icon: string;
}

export function DemoVideoGenerator({ analysis, idea }: Props) {
  const a = analysis;
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const slideRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const slides: Slide[] = [
    // Slide 1: Title
    {
      title: idea,
      subtitle: "AI-Powered Startup Analysis",
      content: (
        <div style={{ fontSize: "20px", opacity: 0.7, marginTop: "16px" }}>
          A complete startup blueprint generated by AI
        </div>
      ),
      narration: `Introducing ${idea}. Let's walk through the complete AI-powered analysis of this startup idea.`,
      bgGradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a78bfa 100%)",
      icon: "🚀",
    },
    // Slide 2: Problem & Opportunity
    {
      title: "The Problem",
      subtitle: a.ideaViability?.problemStatement || "Identifying the core problem",
      content: (
        <div style={{ marginTop: "20px" }}>
          <div style={{ fontSize: "16px", opacity: 0.8, padding: "20px", background: "rgba(255,255,255,0.1)", borderRadius: "12px" }}>
            <div style={{ fontWeight: 600, marginBottom: "8px" }}>Market Opportunity</div>
            {a.ideaViability?.marketOpportunity || "Significant market potential identified"}
          </div>
          <div style={{ marginTop: "16px", display: "flex", alignItems: "center", gap: "12px" }}>
            <div style={{ fontSize: "48px", fontWeight: 800 }}>
              {a.ideaViability?.viabilityScore || "8"}/10
            </div>
            <div style={{ opacity: 0.6 }}>Viability Score</div>
          </div>
        </div>
      ),
      narration: `The core problem: ${a.ideaViability?.problemStatement || "A real market need exists"}. The market opportunity is ${a.ideaViability?.marketOpportunity || "significant"}, with a viability score of ${a.ideaViability?.viabilityScore || 8} out of 10.`,
      bgGradient: "linear-gradient(135deg, #0ea5e9 0%, #0284c7 50%, #0369a1 100%)",
      icon: "💡",
    },
    // Slide 3: Market Size
    {
      title: "Market Analysis",
      subtitle: a.marketAnalysis?.marketSize || "Growing market opportunity",
      content: (
        <div style={{ marginTop: "20px" }}>
          <div style={{ fontSize: "15px", opacity: 0.8, marginBottom: "16px" }}>
            {a.marketAnalysis?.overview || ""}
          </div>
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" as const }}>
            {a.marketAnalysis?.competitors?.slice(0, 4).map((c, i) => (
              <div key={i} style={{
                padding: "12px 16px", background: "rgba(255,255,255,0.1)",
                borderRadius: "8px", fontSize: "14px", fontWeight: 600
              }}>
                {c.name}
              </div>
            ))}
          </div>
          {a.marketAnalysis?.trends && a.marketAnalysis.trends.length > 0 && (
            <div style={{ marginTop: "16px", fontSize: "13px", opacity: 0.6 }}>
              Trends: {a.marketAnalysis.trends.slice(0, 3).join(" • ")}
            </div>
          )}
        </div>
      ),
      narration: `Market size: ${a.marketAnalysis?.marketSize || "substantial"}. Key competitors include ${a.marketAnalysis?.competitors?.slice(0, 3).map(c => c.name).join(", ") || "several players"}. Current trends point to ${a.marketAnalysis?.trends?.[0] || "growing demand"}.`,
      bgGradient: "linear-gradient(135deg, #10b981 0%, #059669 50%, #047857 100%)",
      icon: "📊",
    },
    // Slide 4: Target Audience
    {
      title: "Target Audience",
      subtitle: `${a.targetAudience?.personas?.length || 0} Key Personas Identified`,
      content: (
        <div style={{ marginTop: "20px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
          {a.targetAudience?.personas?.slice(0, 4).map((p, i) => (
            <div key={i} style={{
              padding: "16px", background: "rgba(255,255,255,0.1)",
              borderRadius: "12px",
            }}>
              <div style={{ fontWeight: 700, fontSize: "15px" }}>{p.name}</div>
              <div style={{ fontSize: "12px", opacity: 0.6, marginTop: "4px" }}>{p.age} · {p.occupation}</div>
              <div style={{ fontSize: "12px", opacity: 0.8, marginTop: "8px" }}>
                {p.painPoints?.[0] || ""}
              </div>
            </div>
          ))}
        </div>
      ),
      narration: `We've identified ${a.targetAudience?.personas?.length || "several"} key personas. ${a.targetAudience?.personas?.[0]?.name || "Primary users"} are ${a.targetAudience?.personas?.[0]?.occupation || "professionals"} who struggle with ${a.targetAudience?.personas?.[0]?.painPoints?.[0] || "current solutions"}.`,
      bgGradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 50%, #b45309 100%)",
      icon: "👥",
    },
    // Slide 5: MVP Features
    {
      title: "MVP Features",
      subtitle: `${a.mvpPlan?.features?.filter(f => f.priority === "must-have").length || 0} Must-Have Features`,
      content: (
        <div style={{ marginTop: "20px" }}>
          {a.mvpPlan?.features?.slice(0, 5).map((f, i) => (
            <div key={i} style={{
              display: "flex", alignItems: "center", gap: "12px",
              padding: "10px 0", borderBottom: "1px solid rgba(255,255,255,0.1)"
            }}>
              <div style={{
                padding: "4px 10px", borderRadius: "6px", fontSize: "11px", fontWeight: 600,
                background: f.priority === "must-have" ? "rgba(255,255,255,0.2)" : "rgba(255,255,255,0.08)",
              }}>
                {f.priority}
              </div>
              <div>
                <div style={{ fontWeight: 600, fontSize: "14px" }}>{f.name}</div>
                <div style={{ fontSize: "12px", opacity: 0.6 }}>{f.description}</div>
              </div>
            </div>
          ))}
          {a.mvpPlan?.timeline && (
            <div style={{ marginTop: "16px", fontSize: "13px", opacity: 0.6 }}>
              Timeline: {a.mvpPlan.timeline}
            </div>
          )}
        </div>
      ),
      narration: `The MVP includes ${a.mvpPlan?.features?.length || "several"} features. Must-haves include ${a.mvpPlan?.features?.filter(f => f.priority === "must-have").slice(0, 3).map(f => f.name).join(", ") || "core functionality"}. Estimated timeline: ${a.mvpPlan?.timeline || "3-6 months"}.`,
      bgGradient: "linear-gradient(135deg, #ef4444 0%, #dc2626 50%, #b91c1c 100%)",
      icon: "✅",
    },
    // Slide 6: Tech Stack
    {
      title: "Tech Stack",
      subtitle: "Recommended Technologies",
      content: (
        <div style={{ marginTop: "20px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
          {a.techStack && (["frontend", "backend", "database", "ai", "hosting"] as const).map(k =>
            a.techStack?.[k] ? (
              <div key={k} style={{
                padding: "16px", background: "rgba(255,255,255,0.1)",
                borderRadius: "12px",
              }}>
                <div style={{ fontSize: "11px", textTransform: "uppercase" as const, opacity: 0.5, fontWeight: 600 }}>{k}</div>
                <div style={{ fontWeight: 700, fontSize: "16px", marginTop: "4px" }}>{a.techStack![k]}</div>
              </div>
            ) : null
          )}
        </div>
      ),
      narration: `Recommended tech stack: ${a.techStack?.frontend || "React"} for frontend, ${a.techStack?.backend || "Node.js"} for backend, with ${a.techStack?.database || "PostgreSQL"} as the database. ${a.techStack?.reasoning || ""}`,
      bgGradient: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 50%, #6d28d9 100%)",
      icon: "⚡",
    },
    // Slide 7: Revenue Model
    {
      title: "Revenue Model",
      subtitle: a.monetization?.overview || "Monetization Strategy",
      content: (
        <div style={{ marginTop: "20px", display: "flex", gap: "12px", flexWrap: "wrap" as const }}>
          {a.monetization?.pricingTiers?.map((t, i) => (
            <div key={i} style={{
              flex: "1 1 120px", padding: "20px", background: "rgba(255,255,255,0.1)",
              borderRadius: "12px", textAlign: "center" as const,
            }}>
              <div style={{ fontSize: "13px", opacity: 0.6 }}>{t.name}</div>
              <div style={{ fontSize: "24px", fontWeight: 800, marginTop: "8px" }}>{t.price}</div>
              <div style={{ fontSize: "11px", opacity: 0.5, marginTop: "8px" }}>
                {t.features?.slice(0, 2).join(" · ")}
              </div>
            </div>
          ))}
        </div>
      ),
      narration: `Revenue model: ${a.monetization?.overview || "subscription-based"}. Pricing tiers include ${a.monetization?.pricingTiers?.map(t => `${t.name} at ${t.price}`).join(", ") || "multiple options"}.`,
      bgGradient: "linear-gradient(135deg, #14b8a6 0%, #0d9488 50%, #0f766e 100%)",
      icon: "💰",
    },
    // Slide 8: CTA
    {
      title: "Ready to Build?",
      subtitle: `${idea} — Score: ${a.ideaViability?.viabilityScore || 8}/10`,
      content: (
        <div style={{ marginTop: "20px", textAlign: "center" as const }}>
          <div style={{ fontSize: "18px", opacity: 0.8, marginBottom: "20px" }}>
            {a.pitchDeck?.solution || "A complete startup blueprint, generated in seconds."}
          </div>
          <div style={{
            display: "inline-block", padding: "14px 32px",
            background: "rgba(255,255,255,0.2)", borderRadius: "12px",
            fontWeight: 700, fontSize: "16px", backdropFilter: "blur(10px)",
          }}>
            Try AI Product Manager →
          </div>
          <div style={{ marginTop: "20px", fontSize: "13px", opacity: 0.5 }}>
            ai-product-manager-support.lovable.app
          </div>
        </div>
      ),
      narration: `${idea} has real potential. With the right execution, this could be a game-changer. Get started with AI Product Manager to build your startup today.`,
      bgGradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a78bfa 100%)",
      icon: "🎯",
    },
  ];

  const totalSlides = slides.length;
  const slideDuration = 4000; // 4 seconds per slide

  const nextSlide = useCallback(() => {
    setCurrentSlide(prev => {
      if (prev >= totalSlides - 1) {
        setIsPlaying(false);
        return prev;
      }
      return prev + 1;
    });
  }, [totalSlides]);

  const prevSlide = useCallback(() => {
    setCurrentSlide(prev => Math.max(0, prev - 1));
  }, []);

  useEffect(() => {
    if (isPlaying) {
      intervalRef.current = setInterval(nextSlide, slideDuration);
    }
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [isPlaying, nextSlide]);

  const togglePlay = () => {
    if (currentSlide >= totalSlides - 1) {
      setCurrentSlide(0);
    }
    setIsPlaying(prev => !prev);
  };

  const toggleFullscreen = () => {
    if (!containerRef.current) return;
    if (!isFullscreen) {
      containerRef.current.requestFullscreen?.();
      setIsFullscreen(true);
    } else {
      document.exitFullscreen?.();
      setIsFullscreen(false);
    }
  };

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener("fullscreenchange", handler);
    return () => document.removeEventListener("fullscreenchange", handler);
  }, []);

  // Keyboard controls
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight" || e.key === " ") {
        e.preventDefault();
        nextSlide();
      }
      if (e.key === "ArrowLeft") {
        e.preventDefault();
        prevSlide();
      }
      if (e.key === "Escape") {
        setIsPlaying(false);
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [nextSlide, prevSlide]);

  const downloadSlides = async () => {
    if (!slideRef.current) return;
    try {
      const canvas = await html2canvas(slideRef.current, {
        scale: 2,
        backgroundColor: null,
        useCORS: true,
        logging: false,
      });
      const link = document.createElement("a");
      link.download = `demo-slide-${currentSlide + 1}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
      toast.success("Slide image downloaded!");
    } catch {
      toast.error("Failed to capture slide");
    }
  };

  const slide = slides[currentSlide];
  const progress = ((currentSlide + 1) / totalSlides) * 100;
  const shareText = `🎥 AI generated a 30-second product demo for my startup "${idea}"!\n\nComplete with storyboard, narration, and visual walkthrough.\n\nTry it yourself:`;

  return (
    <Card className="overflow-hidden">
      <CardHeader className="flex flex-row items-start justify-between">
        <div>
          <CardTitle className="flex items-center gap-2">
            <Video className="h-5 w-5 text-primary" />
            AI Demo Video Generator
          </CardTitle>
          <CardDescription>Auto-generated product walkthrough with storyboard & narration</CardDescription>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={downloadSlides}>
            <Download className="h-3 w-3 mr-1" />
            Save Slide
          </Button>
          <Button variant="outline" size="sm" onClick={() => shareOnLinkedIn(shareText)}>
            <Linkedin className="h-3 w-3 mr-1" />
            Share
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Video Player */}
        <div ref={containerRef} className="relative rounded-xl overflow-hidden" style={{ aspectRatio: "16/9" }}>
          {/* Slide Content */}
          <AnimatePresence mode="wait">
            <motion.div
              key={currentSlide}
              ref={slideRef}
              initial={{ opacity: 0, x: 40 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -40 }}
              transition={{ duration: 0.4, ease: "easeInOut" }}
              style={{
                position: "absolute", inset: 0,
                background: slide.bgGradient,
                color: "white",
                padding: isFullscreen ? "60px" : "32px",
                display: "flex", flexDirection: "column", justifyContent: "center",
              }}
            >
              <div style={{ fontSize: isFullscreen ? "48px" : "32px", marginBottom: "8px" }}>{slide.icon}</div>
              <h2 style={{
                fontSize: isFullscreen ? "40px" : "24px",
                fontWeight: 800, lineHeight: 1.2, marginBottom: "8px"
              }}>
                {slide.title}
              </h2>
              <p style={{
                fontSize: isFullscreen ? "20px" : "14px",
                opacity: 0.8, marginBottom: "4px"
              }}>
                {slide.subtitle}
              </p>
              <div style={{ fontSize: isFullscreen ? "16px" : "12px" }}>
                {slide.content}
              </div>
            </motion.div>
          </AnimatePresence>

          {/* Progress Bar */}
          <div style={{
            position: "absolute", bottom: 0, left: 0, right: 0, height: "4px",
            background: "rgba(255,255,255,0.2)",
          }}>
            <motion.div
              style={{ height: "100%", background: "white" }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>

          {/* Slide Counter */}
          <div style={{
            position: "absolute", top: "12px", right: "12px",
            background: "rgba(0,0,0,0.4)", borderRadius: "8px",
            padding: "4px 10px", fontSize: "12px", color: "white", fontWeight: 600,
          }}>
            {currentSlide + 1} / {totalSlides}
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Button variant="outline" size="icon" onClick={prevSlide} disabled={currentSlide === 0}>
              <SkipBack className="h-4 w-4" />
            </Button>
            <Button variant="default" size="icon" onClick={togglePlay}>
              {isPlaying ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
            </Button>
            <Button variant="outline" size="icon" onClick={nextSlide} disabled={currentSlide >= totalSlides - 1}>
              <SkipForward className="h-4 w-4" />
            </Button>
            <Button variant="outline" size="icon" onClick={toggleFullscreen}>
              {isFullscreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
            </Button>
          </div>
          <Badge variant="outline" className="text-xs">
            ~{Math.ceil(totalSlides * 4)}s walkthrough
          </Badge>
        </div>

        {/* Slide Thumbnails */}
        <div className="flex gap-2 overflow-x-auto pb-2">
          {slides.map((s, i) => (
            <button
              key={i}
              onClick={() => { setCurrentSlide(i); setIsPlaying(false); }}
              className={`shrink-0 rounded-lg overflow-hidden border-2 transition-all ${
                i === currentSlide ? "border-primary ring-2 ring-primary/30" : "border-transparent opacity-60 hover:opacity-100"
              }`}
              style={{ width: "80px", height: "45px" }}
            >
              <div style={{
                width: "100%", height: "100%",
                background: s.bgGradient,
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "16px",
              }}>
                {s.icon}
              </div>
            </button>
          ))}
        </div>

        {/* Narration Script */}
        <div className="p-4 rounded-lg bg-muted/50 border">
          <div className="flex items-center justify-between mb-2">
            <h4 className="font-semibold text-sm">🎙️ Narration Script (Slide {currentSlide + 1})</h4>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                navigator.clipboard.writeText(slide.narration);
                toast.success("Narration copied!");
              }}
            >
              <Share2 className="h-3 w-3 mr-1" />
              Copy
            </Button>
          </div>
          <p className="text-sm text-muted-foreground italic">"{slide.narration}"</p>
        </div>

        {/* Full Script */}
        <details className="group">
          <summary className="cursor-pointer text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
            📄 View Full Narration Script
          </summary>
          <div className="mt-3 p-4 rounded-lg bg-muted/50 border space-y-3">
            {slides.map((s, i) => (
              <div key={i} className="text-sm">
                <span className="font-medium text-primary">Slide {i + 1} ({s.title}):</span>
                <p className="text-muted-foreground mt-1 italic">"{s.narration}"</p>
              </div>
            ))}
            <Button
              variant="outline"
              size="sm"
              className="mt-2"
              onClick={() => {
                const full = slides.map((s, i) => `Slide ${i + 1} (${s.title}):\n"${s.narration}"`).join("\n\n");
                navigator.clipboard.writeText(full);
                toast.success("Full script copied!");
              }}
            >
              <Share2 className="h-3 w-3 mr-1" />
              Copy Full Script
            </Button>
          </div>
        </details>

        {/* Share CTA */}
        <div className="text-center p-4 rounded-lg bg-primary/5 border border-primary/10">
          <p className="text-sm text-muted-foreground mb-2">
            🎥 Screen-record this walkthrough and share it on LinkedIn!
          </p>
          <div className="flex justify-center gap-2 flex-wrap">
            {typeof navigator !== "undefined" && navigator.share && (
              <Button size="sm" onClick={() => { shareNative(shareText); }}>
                <Share2 className="h-4 w-4 mr-1" />
                Share
              </Button>
            )}
            <Button size="sm" variant={typeof navigator !== "undefined" && navigator.share ? "outline" : "default"} onClick={() => shareOnLinkedIn(shareText)}>
              <Linkedin className="h-4 w-4 mr-1" />
              LinkedIn
            </Button>
            <Button size="sm" variant="outline" onClick={() => shareOnTwitter(shareText)}>
              <Twitter className="h-4 w-4 mr-1" />
              Twitter
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
